add new logic to the terragrunt container

diff --git a/.github/workflows/terragrunt-deploy.yml b/.github/workflows/terragrunt-deploy.yml
--- a/.github/workflows/terragrunt-deploy.yml
+++ b/.github/workflows/terragrunt-deploy.yml
@@ -2,6 +2,11 @@ name: BlogDevOpsHub Workflow
 
 on:
   workflow_dispatch:
+    inputs:
+      approve:
+        description: 'Approve deployment'
+        required: false
+        default: 'false'
 
 jobs:
   setup-aws:
@@ -41,14 +46,18 @@ jobs:
     steps:
       - name: Wait for Manual Approval
         id: approval
-        uses: brunohigino06/manual-approval-action@v1
-        with:
-          message: "Click the button to approve deployment"
+        run: |
+          if [ "${{ github.event.inputs.approve }}" == "true" ]; then
+            echo "Manual approval granted."
+          else
+            echo "::warning:: Manual approval is required. Click the 'Approve deployment' button to proceed."
+            exit 1
+          fi
 
   terragrunt-apply:
     runs-on: ubuntu-latest
     needs: wait-for-approval
-    if: success() && github.event_name == 'workflow_dispatch' || github.event.inputs.approve == 'true' && needs.wait-for-approval.result == 'success'
+    if: success() && (github.event_name == 'workflow_dispatch' || github.event.inputs.approve == 'true') && needs.wait-for-approval.result == 'success'
     steps:
       - name: Checkout terragrunt action
         uses: actions/checkout@v2
